### ISSUE TITLE
No tracing headers sent if proxy_pass is within a "if" statement block.

### ISSUE THREAD

**Issue by jonphilpott** [DataDog/nginx-datadog#43]
We have several nginx configurations that have a line like the following:

```
    if (!-f $request_filename) {
      proxy_pass http://test;
      break;
    }
```

In this case, when the proxy_pass is within the context of an `if` block, there are no tracing headers sent to the downstream. If the `if` block is removed, we do see headers propagated correctly.

**Comment by dgoffredo** [comment]
Hi Jonathan,

That's probably because the `proxy_pass` handler that our module uses to "hijack" the behavior of the directive is not allowed in `if` contexts: https://github.com/DataDog/nginx-datadog/blob/582d1cc992050246dc93c3e6fe80edafa8b86a1c/src/ngx_http_datadog_module.cpp#L54-L73

I'm surprised that nginx accepted the configuration. It looks like nginx will skip over mismatched configuration situations, i.e. multiply defined directives are effectively overloaded: https://github.com/nginx/nginx/blob/c37fdcdd1e1527d2c98cc68a978cf928589c7330/src/core/ngx_conf_file.c#L395-L397

It's a policy of this module that datadog-specific directives shall not work in `if` contexts, but I think that the module might still be able to "hijack" `proxy_pass` directives in `if` contexts, if I modify the C++ code above.

I can play with this tomorrow.

Please submit a bug report to Datadog as well: https://help.datadoghq.com/hc/en-us/requests/new

**Comment by dgoffredo** [comment]
Uh oh.
```
23      location /http {
24          if (-f /etc/os-release) {
25              proxy_pass "http://http:8080";
26              break;
27          }
28          return 200 "YOLO!\n";
29      }
```
```
2023/10/05 19:23:47 [emerg] 1#1: "proxy_set_header" directive is not allowed here in /etc/nginx/nginx.conf:25
```
I changed the definition of our "hijacked" `proxy_pass` so that it is allowed in `if` contexts, and this happened.

Our `proxy_pass` works by inserting `proxy_set_header` directives into the configuration at the same level where the `proxy_pass` was encountered. The `proxy_set_header` directives instruct nginx to send tracing-related propagation headers.

The problem is, while [proxy_pass][1] is allowed in `if` contexts, [proxy_set_header][2] is not.

This is quite a problem. It's also not the [first time][3] that our strategy of inserting `proxy_set_header` directives was problematic.

I'll have to talk this over with my teammates.

In the mean time, could you please share more of your nginx configuration? Maybe we can come up with a workaround that has the same logic as your current configuration, but doesn't run afoul with this bug.

[1]: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
[2]: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
[3]: https://github.com/DataDog/nginx-datadog/issues/19

**Comment by jonphilpott** [comment]
I don't think I can share more of the config unfortunately, but essentially we have an http root setup and if we don't have a matching file in the root, we want to proxy pass to our backend.

**Comment by dgoffredo** [comment]
Here is a `try_files`-based workaround that works in my setup:
```nginx
load_module modules/ngx_http_datadog_module.so;

worker_processes 1;

events {
    worker_connections  1024;
}

error_log stderr info;

http {
    server {
        listen       80;

        root /usr/share/nginx/html

        location @backend {
            proxy_pass "http://http:8080";
        }

        location / {
            try_files $uri @backend;
        }
    }
}
```

**Comment by jonphilpott** [comment]
awesome, we'll do some tests with this
