### ISSUE TITLE
Getting "Could not parse Remote Configuration response body" on AL2023

### ISSUE THREAD

**Issue by gugaiz** [DataDog/nginx-datadog#61]
I built the nginx module using the changes on this [PR](https://github.com/DataDog/nginx-datadog/pull/54) for the image `amazonlinux_2023.3.20240219.0`. The build finished without issues but when running the module I am getting

```
2024/02/23 15:04:46 [error] 14490#14493: datadog: Could not parse Remote Configuration response body
```
I got the image from [here](https://gallery.ecr.aws/amazonlinux/amazonlinux) because it is not available on Docker hub

Any ideas?

**Comment by dgoffredo** [comment]
I vaguely recall this happening when the Datadog Agent returns 200 OK with a body that is not JSON, and is instead a plaintext error message about some unexpected gRPC error status received from Datadog's intake.

The log message in the tracer is coming from [here][1]. The message would be more helpful if it printed (an excerpt of) the response body.

Since you are building from source, perhaps you can confirm whether the error message is as I suspect. In `nginx-datadog`, `dd-trace-cpp` is a git submodule. Point it at a branch that has the following change: the error message [here][1] should print the response body, as is done [here][2].

If it's the error that I think it is, then we can find a solution... ah, wait. I think that @dmehala fixed this in https://github.com/DataDog/dd-trace-cpp/pull/95. Perhaps all we need to do is release those changes (in dd-trace-cpp), update the submodule in nginx-datadog, and it will be fixed.

For now, please try building nginx-datadog with the dd-trace-cpp submodule pointed at the current `main` branch of dd-trace-cpp. See if that fixes the error message.

[1]: https://github.com/DataDog/dd-trace-cpp/blob/6dacac2922d08f455f10807f22aa0e98832d20d5/src/datadog/datadog_agent.cpp#L430
[2]: https://github.com/DataDog/dd-trace-cpp/blob/6dacac2922d08f455f10807f22aa0e98832d20d5/src/datadog/datadog_agent.cpp#L417-L418

**Comment by dgoffredo** [comment]
I plan on cutting a new release today, so you'll just be able to use that.

**Comment by dgoffredo** [comment]
Try today's new release: https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.5

**Comment by dgoffredo** [comment]
I'll take a look at your Amazon Linux PR again today. Pardon the delay, the team is strapped.
